version: "2"

services: 
    mysql:
        image: mysql
        ports:
            - 3308:3306
        command: --default-authentication-plugin=mysql_native_password        
        environment: 
            MYSQL_ROOT_PASSWORD: porquinho   

    api:
        build: ./api 
        ports: 
            - 3001:3000
        volumes: 
            - ./api:/var/www/api
        links: 
            - mysql    
